{% set version = "0.4.5" %}
{% set torch_version = "1.10" %}

package:
  name: fairscale
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/fairscale/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0b251abb1b0d954ee4c85dc4b86f3430df1a673e63997aaa29d10da510e3d65d

build:
  number: 0
  # no pytorch on windows in conda-forge, see
  # https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32
  skip: true  # [win]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

requirements:
  build:
    - sysroot_linux-64 2.17           # [linux]
    # compilers only needed for CUDA extensions
    - {{ compiler('cxx') }}           # [cuda_compiler_version != "None"]
    - {{ compiler('cuda') }}          # [cuda_compiler_version != "None"]
  host:
    - python
    - pip
    # host-dependency only needed for compiling CUDA extensions
    - pytorch {{ torch_version }}.*
    - pytorch-gpu                     # [cuda_compiler_version != "None"]
  run:
    - python
    # due to lack of ABI, we need to fix build-time and runtime to the same version
    # (waiting for conda-forge/conda-forge-pinning-feedstock#1890)
    - pytorch {{ torch_version }}.*
    - pytorch-gpu                     # [cuda_compiler_version != "None"]
    - pytorch-cpu                     # [cuda_compiler_version == "None"]

test:
  requires:
    - pytest
    - parameterized
    - scikit-learn
  source_files:
    - tests
  commands:
    # TODO: re-enable tests for unix
    - pytest tests  # [linux]
  imports:
    - fairscale
    - fairscale.nn
    - fairscale.nn.data_parallel
    - fairscale.nn.model_parallel
    - fairscale.nn.pipe
    - fairscale.nn.pipe.balance
    - fairscale.nn.pipe.skip
    - fairscale.optim

about:
  home: https://github.com/facebookresearch/fairscale
  license: BSD-3-Clause
  license_file: LICENSE
  summary: PyTorch extensions for high performance and large scale training.
  dev_url: https://github.com/facebookresearch/fairscale
  doc_url: https://fairscale.readthedocs.io/

extra:
  recipe-maintainers:
    - h-vetinari
